services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ml_api_db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - ml-api-network

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ml_api_db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - ml-api-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ml_api_db
    ports:
      - "5432:5432"
    networks:
      - ml-api-network

volumes:
  postgres_data:

networks:
  ml-api-network:
    driver: bridge 